declare module '*.scss'
declare module '*.svg'
declare module '*.gif'
declare module '*.png'
declare module '*.json'
declare module 'top-sdk-js-v2'
declare module '@metamask/jazzicon'
declare module '@metamask/eth-token-tracker'
// declare module '@zondax/filecoin-signing-tools'
declare module '@filecoin-shipyard/lotus-client-provider-browser'
declare module '@filecoin-shipyard/lotus-client-schema'
